install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
script:
  - hugo
deploy:
  skip_cleanup: true
  keep_history: true
  github_token: $TEALINUXOS_ACCESS_TOKEN
  repo: $REPO_OWNER/$REPO_NAME
  name: $REPO_OWNER
  email: akhmadbasir5@gmail.com
  provider: pages
  local_dir: public
  on:
    branch: gh-pages
after_deploy:
  - git clone $TARGET_REPO product
  - cd product
  - git log --oneline --graph -n 20
  
