go:
  - "lts/*"
branches:
  only:
    - master
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
before_script:
  - git config --global user.name 'tealinuxos via Travis CI'
  - git config --global user.email 'mailpakgasing@gmail.com'
script:
  - hugo
  - ls -al public
  - cd public
  - git init
  - git remote add origin https://github.com/tealinuxos/tealinuxos.github.io.git; fi
  - git add -A .; fi
  - git commit -m 'Site updated'; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push --force --quiet origin master; fi

#after_success:
#  - echo "now in directory : $(pwd)"
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd public; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git init; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git remote add origin https://github.com/tealinuxos/tealinuxos.github.io.git; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git add -A .; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git commit -m 'Site updated'; fi
#  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push --force --quiet origin master; fi
