install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
# ---------  
before_deploy:
  # Set up git user name and tag this commit
  - git config --global user.name "TeaLinuxOS - Travis Pipeline"
  - git config --global user.email "akhmadbasir5@gmail.com"
# ---------
script:
  - hugo  
# ---------
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: public
  repo: $REPO
