baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "TeaLinux OS"

themeDir = "themes"
theme = "teaxi"

sectionPagesMenu = "main"

paginate = 1

[params]
    logo = "img/logo.png"
    iconLaporhama = "icon/icon-laporhama.svg"
    iconDaun = "icon/daun.png"
    iconAntipiracy = "icon/ap.png"
    iconCommunity = "icon/c.png"
    iconHQ = "icon/highquality.png"
    iconNutrition = "icon/nutrition.png"
    maskot = "img/maskot.png"
    teaInstaller = "fitur/2.2.png"
    teaTheme = "fitur/2.1.png"
    laporhama = "fitur/3.png"
    desktop = "img/desktop.png"
#    resep = "img/resep.jpg"
#    artwork = "img/artwork.jpg"
#    riset = "img/riset.jpg"
#    pemaketan = "img/pemaketan.jpg"
#    dokumentasi = "img/dokumentasi.jpg"
    langkah1 = "img/langkah1.jpg"
    langkah2 = "img/langkah2.jpg"
#    langkah3 = "img/langkah3.jpg"
    mockup = "img/mockup-kosong.jpeg"
    mockupProfile = "img/mockup-profile.png"

[menu]
    # Navbar Menus
    [[menu.title]]
        name    = "About"
        Identifier = "/dokumentasi"
    [[menu.title]]
        name    = "Service"
        Identifier = "/dokumentasi/page/2"


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]