baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "TeaLinux OS"

themeDir = "themes"
theme = "teaxi"

[params]
    logo = "img/logo.png"
    iconLaporhama = "icon/icon-laporhama.svg"
    iconDaun = "icon/daun.png"
    iconAntipiracy = "icon/antipiracy.svg"
    iconCommunity = "icon/community.svg"
    iconHQ = "icon/HQ.svg"
    iconNutrition = "icon/Nutrition.svg"
    maskot = "img/maskot.png"
#    teaInstaller = "img/tea-installer.jpg"
#    teatheme = "img/tea-theme.jpg"
#    laporhama = "img/laporhama.jpg"
#    resep = "img/resep.jpg"
#    artwork = "img/artwork.jpg"
#    riset = "img/riset.jpg"
#    pemaketan = "img/pemaketan.jpg"
#    dokumentasi = "img/dokumentasi.jpg"
    langkah1 = "img/langkah1.jpg"
    langkah2 = "img/langkah2.jpg"
#    langkah3 = "img/langkah3.jpg"
    mockup = "img/mockup-kosong.jpeg"

